export const CONSTANTS = {
    PLAYER_SIZE: 0.8,
    PLAYER_RADIUS_FACTOR: 0.35,
    ANIMATION_SPEED: 8.0,
    WALK_ANIMATION_INTERVAL: 0.12,
    FOG_UNVISITED: 0.90,
    FOG_VISITED: 0.60,
    FOG_LIGHT: 0.40,
    STABILITY_THRESHOLD: 1.5,
    STREAK_TIME_THRESHOLD: 20.0,
    DOOR_ANIMATION_DURATION: 0.5,
    COLLISION_EPSILON: 0.01
};
